version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_KEY: ${RAILWAY_SERVICE_ID} # Comes from .env
    ports:
      - "3000:3000"
    env_file:
      - .env  # Load all secrets from your .env file
